sudo: false
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
script:
  - npm run lint
  - npm run cover
